// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4kmxCBuu0cZ_OEKZNBrVrzms98h81pJc',
    appId: '1:1098006028275:web:a65a6a126429e84d8efc86',
    messagingSenderId: '1098006028275',
    projectId: 'music-app-ff87d',
    authDomain: 'music-app-ff87d.firebaseapp.com',
    storageBucket: 'music-app-ff87d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3nx88aEmWABPdqEc2RmbxPCAZe9j0-d8',
    appId: '1:1098006028275:android:93764bbb2ed45b088efc86',
    messagingSenderId: '1098006028275',
    projectId: 'music-app-ff87d',
    storageBucket: 'music-app-ff87d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqVCY96Oaasa7OrCSIuYlmUKtG7dWPvaY',
    appId: '1:1098006028275:ios:65abd23b2e08b67f8efc86',
    messagingSenderId: '1098006028275',
    projectId: 'music-app-ff87d',
    storageBucket: 'music-app-ff87d.firebasestorage.app',
    iosBundleId: 'com.example.musicAppAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqVCY96Oaasa7OrCSIuYlmUKtG7dWPvaY',
    appId: '1:1098006028275:ios:65abd23b2e08b67f8efc86',
    messagingSenderId: '1098006028275',
    projectId: 'music-app-ff87d',
    storageBucket: 'music-app-ff87d.firebasestorage.app',
    iosBundleId: 'com.example.musicAppAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4kmxCBuu0cZ_OEKZNBrVrzms98h81pJc',
    appId: '1:1098006028275:web:87da51e64087f5c18efc86',
    messagingSenderId: '1098006028275',
    projectId: 'music-app-ff87d',
    authDomain: 'music-app-ff87d.firebaseapp.com',
    storageBucket: 'music-app-ff87d.firebasestorage.app',
  );
}
